{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"The following error originated from your application code, not from Cypress.    > $.plot is not a function  When Cypress detects uncaught errors originating from your application it will automatically fail the current test.  This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.  https://on.cypress.io/uncaught-exception-from-application  Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Handle Tables`","children":[{"name":"Handle Tables \"before each\" hook: Login for \"Check Number Rows & Columns\"","uid":"a9a73a88fb2b4443","parentUid":"c71bb82668565bd7c8f8ecc6d6b32c3d","status":"failed","time":{"start":1718603243000,"stop":1718603243000,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"c71bb82668565bd7c8f8ecc6d6b32c3d"},{"name":"Timed out retrying after 4000ms: Expected to find element: `//a[text()=' Customers']`, but never found it.  Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Handle Tables`","children":[{"name":"Handle Tables \"before each\" hook: Login for \"Pagination\"","uid":"cbec2c94d6caf933","parentUid":"775bb0d9fe29ee7020c309909cbaed55","status":"failed","time":{"start":1718603754000,"stop":1718603754000,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"Handle Tables \"before each\" hook: Login for \"Check cell data from specific row & Column\"","uid":"62224e1d541e578","parentUid":"775bb0d9fe29ee7020c309909cbaed55","status":"failed","time":{"start":1718604541000,"stop":1718604541000,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"775bb0d9fe29ee7020c309909cbaed55"},{"name":"`cy.visit()` failed trying to load:  https://demo.opencart.com/admin/index.php  The response we received from your web server was:    > 429: Too Many Requests  This was considered a failure because the status code was not `2xx`.  If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`  Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Handle Tables`","children":[{"name":"Handle Tables \"before each\" hook: Login for \"Read all the rows & Columns data in the first page\"","uid":"f0d90c0850a1e7bf","parentUid":"e6ca4802f4b8406c8db72895e5fe773a","status":"failed","time":{"start":1718605095000,"stop":1718605095000,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"e6ca4802f4b8406c8db72895e5fe773a"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}